specfile_path: distrobox.spec
files_to_sync:
  - distrobox.spec
  - .packit.yaml
upstream_package_name: distrobox
downstream_package_name: distrobox
actions:
    post-upstream-clone: "wget https://src.fedoraproject.org/rpms/distrobox/raw/main/f/distrobox.spec -O distrobox.spec"
srpm_build_deps:
  - wget
  
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    copy_upstream_release_description: true
    metadata:
      dist-git-branch: private-packit-test
